language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - dist: precise
      php: 5.3
    - dist: trusty
      php: 5.4
    - dist: trusty
      php: 5.5
    - dist: xenial
      php: 5.6
    - dist: xenial
      php: 7.0
    - dist: bionic
      php: 7.1
    - dist: bionic
      php: 7.2
    - dist: bionic
      php: 7.3
    - dist: bionic
      php: 7.4
      env: BC_TESTS=true
    - dist: bionic
      php: nightly
      env: platform=ignore
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  # disable Xdebug if present
  - phpenv config-rm xdebug.ini || echo "Xdebug not present"

install:
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  - if [ "$platform" == "ignore" ]; then flags="$flags --ignore-platform-reqs"; fi
  - composer install $flags

script:
  - ( set -e; for f in $(find src/ -name *.php); do php -l "$f" || exit 1; done )
  - composer run-script test
  - if [ "$BC_TESTS" == "true" ]; then composer run-script test:bc; fi
